name: Push Both

on:
  workflow_call:
  workflow_dispatch:

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Install Oras
        run: |
          # https://oras.land/docs/installation/#linux
          VERSION="1.2.2"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_*.tar.gz oras-install/
      - name: Push to 2
        run: |
          oras push ghcr.io/shino/package-push-test2:oras
          oras push ghcr.io/shino/package-push-test1:oras
